const fs = require('fs');

const myKeys = {
  title: 'ငွေပေးချေမှု အောင်မြင်ပါသည်!',
  success_message: 'သင့်အော်ဒါကို အတည်ပြုပြီး ငွေပေးချေမှုလည်း အောင်မြင်ပါပြီ။',
  order_confirmed: 'သင့်အော်ဒါကို အတည်ပြုပြီးပါပြီ',
  order_number: 'အော်ဒါနံပါတ်',
  print: 'ပရင့်ထုတ်ရန်',
  download_pdf: 'PDF ဒေါင်းလုတ်ရန်',
  downloading: 'ဒေါင်းလုတ်နေသည်...',
  continue_shopping: 'စျေးဝယ်ဆက်လုပ်ရန်',
  track_order: 'အော်ဒါ ခြေရာခံရန်',
  order_summary: 'အော်ဒါ အကျဉ်းချုပ်',
  shipping_to: 'ပို့ဆောင်မည့်လိပ်စာ',
  total_paid: 'စုစုပေါင်း ပေးချေပြီးငွေ',
  subtotal: 'ကုန်ပစ္စည်းစုစုပေါင်း',
  shipping: 'ပို့ဆောင်ခ',
  tax: 'အခွန်',
  payment_method: 'ငွေပေးချေမှုနည်းလမ်း',
  thank_you: 'မှာယူမှုအတွက် ကျေးဇူးတင်ပါသည်!',
  loading_details: 'ငွေပေးချေမှုအသေးစိတ်ကို ဖွင့်နေပါသည်...',
  load_error_title: 'ပြေစာဖွင့်ရာတွင် အမှားဖြစ်နေပါသည်',
  load_failed: 'အော်ဒါအသေးစိတ်ကို ဖွင့်၍မရပါ။',
  invalid_order: 'အော်ဒါအချက်အလက် မမှန်ကန်ပါ။',
  try_again: 'ထပ်မံကြိုးစားရန်',
  view_orders: 'အော်ဒါများကြည့်ရန်',
  print_missing: 'ပရင့်ထုတ်ရန်အချက်အလက် မတွေ့ပါ။ PDF အဖြစ် ဒေါင်းလုတ်ရန် ထပ်စမ်းပါ။',
  pdf_failed: 'PDF ဒေါင်းလုတ်၍မရပါ။ ထပ်မံကြိုးစားပါ။',
  receipt_title_with_order: 'ငွေပေးချေမှုပြေစာ - {{orderNumber}}',
  share_title: 'ငွေပေးချေမှုပြေစာ - {{orderNumber}}',
  share_text: '{{orderNumber}} အော်ဒါအတွက် ငွေပေးချေမှုအတည်ပြုချက်',
  share: 'မျှဝေရန်',
  copied: 'ကူးယူပြီးပါပြီ',
  link_copied: 'လင့်ခ်ကူးယူပြီးပါပြီ',
  share_payment_slip: 'ငွေပေးချေမှုပြေစာ မျှဝေရန်',
  receipt_title: 'ငွေပေးချေမှုပြေစာ',
  receipt_heading: 'ငွေပေးချေမှုပြေစာ',
  platform_name: 'Pyonea B2B ဈေးကွက်',
  platform_address: '၁၉ လမ်း၊ အောင်မြေသာစံမြို့နယ်၊ မန္တလေး၊ မြန်မာ | +95 9 792 115 547',
  order_information: 'အော်ဒါအချက်အလက်',
  payment_information: 'ငွေပေးချေမှုအချက်အလက်',
  customer_information: 'ဝယ်ယူသူအချက်အလက်',
  shipping_address: 'ပို့ဆောင်မည့်လိပ်စာ',
  order_date: 'အော်ဒါတင်သည့်ရက်',
  status: 'အခြေအနေ',
  confirmed: 'အတည်ပြုပြီး',
  payment_date: 'ငွေပေးချေသည့်ရက်',
  reference_id: 'ကိုးကားနံပါတ်',
  paid: 'ပေးချေပြီး',
  not_available: 'မရှိပါ',
  invalid_date: 'ရက်စွဲမမှန်ပါ',
  order_items: 'အော်ဒါပစ္စည်းများ',
  item: 'ပစ္စည်း',
  qty: 'အရေအတွက်',
  price: 'ဈေးနှုန်း',
  total: 'စုစုပေါင်း',
  unknown_product: 'အမည်မသိ ပစ္စည်း',
  sku: 'SKU',
  no_items: 'ဤအော်ဒါတွင် ပစ္စည်းမတွေ့ပါ။',
  tax_with_rate: 'အခွန် ({{rate}}%)',
  footer_thanks: 'သင့်ဝယ်ယူမှုအတွက် ကျေးဇူးတင်ပါသည်!',
  generated_receipt: 'ဤပြေစာသည် စနစ်မှ အလိုအလျောက်ထုတ်ပေးထားသော ပြေစာဖြစ်ပြီး လက်မှတ်မလိုအပ်ပါ။',
  support_line: 'မေးမြန်းလိုပါက support@pyonea.com | +95 9 792 115 547 သို့ ဆက်သွယ်ပါ။',
  whats_next: 'နောက်တစ်ဆင့်မှာ ဘာဖြစ်မလဲ?',
  order_processing: 'အော်ဒါပြင်ဆင်နေပါသည်',
  order_processing_desc: 'ရောင်းချသူသည် ၂၄ နာရီအတွင်း သင့်ပစ္စည်းများကို ပြင်ဆင်ပေးပါမည်။',
  shipping_updates: 'ပို့ဆောင်မှုအခြေအနေ',
  shipping_updates_desc: 'သင့်အော်ဒါအခြေအနေကို အော်ဒါစာမျက်နှာမှ စစ်ဆေးနိုင်ပါသည်။',
  quick_actions: 'အမြန်လုပ်ဆောင်ရန်',
  view_all_orders: 'အော်ဒါအားလုံးကြည့်ရန်',
  close: 'ပိတ်ရန်',
  need_help: 'အကူအညီလိုပါသလား?',
  support_help: 'သင့်အော်ဒါနှင့်ပတ်သက်၍ ကျွန်ုပ်တို့၏ support team က ကူညီပေးနိုင်ပါသည်။',
  support_phone: 'ဖုန်း: +95 9 792 115 547',
  support_email: 'အီးမေးလ်: support@pyonea.com',
  support_hours: 'အချိန်: နေ့စဉ် မနက် ၈:၀၀ မှ ည ၈:၀၀ အထိ'
};

const data = JSON.parse(fs.readFileSync('src/locales/my.json', 'utf8'));
data.payment_success = { ...(data.payment_success || {}), ...myKeys };
fs.writeFileSync('src/locales/my.json', `${JSON.stringify(data, null, 2)}\n`, 'utf8');
